// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
)

type Option struct {
	ID         int32  `json:"id"`
	QuestionID int32  `json:"question_id"`
	OptionKey  string `json:"option_key"`
	OptionText string `json:"option_text"`
	IsCorrect  bool   `json:"is_correct"`
}

type Pdf struct {
	ID          int32          `json:"id"`
	UserID      int32          `json:"user_id"`
	Filename    string         `json:"filename"`
	UploadedAt  sql.NullTime   `json:"uploaded_at"`
	Status      sql.NullString `json:"status"`
	TextContent sql.NullString `json:"text_content"`
}

type Question struct {
	ID           int32  `json:"id"`
	PdfID        int32  `json:"pdf_id"`
	QuestionText string `json:"question_text"`
}

type User struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
}
