// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: options.sql

package repository

import (
	"context"
)

const insertOption = `-- name: InsertOption :exec
INSERT INTO options (question_id, option_key, option_text, is_correct)
VALUES ($1, $2, $3, $4)
`

type InsertOptionParams struct {
	QuestionID int32  `json:"question_id"`
	OptionKey  string `json:"option_key"`
	OptionText string `json:"option_text"`
	IsCorrect  bool   `json:"is_correct"`
}

func (q *Queries) InsertOption(ctx context.Context, arg InsertOptionParams) error {
	_, err := q.db.ExecContext(ctx, insertOption,
		arg.QuestionID,
		arg.OptionKey,
		arg.OptionText,
		arg.IsCorrect,
	)
	return err
}
