// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: questions.sql

package repository

import (
	"context"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (pdf_id, question_text)
VALUES ($1, $2)
RETURNING id
`

type CreateQuestionParams struct {
	PdfID        int32  `json:"pdf_id"`
	QuestionText string `json:"question_text"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createQuestion, arg.PdfID, arg.QuestionText)
	var id int32
	err := row.Scan(&id)
	return id, err
}
